### PR TITLE
Improve Phoenix integration

### PR DESCRIPTION
**Pull request by gugahoa**
## Description
This PR has two features:
1. Enable Go To Definition when inside a Phoenix `scope`;
2. Override Auto Complete for the controller argument if the function is one of the predefined ones from Phoenix.Route;
3. Override Auto Complete for the action argument if the function is one of the predefined ones from Phoenix.Route.

The PR is in draft, anything can be discussed. I though this could be a valuable contribution given the widespread usage of Phoenix.

## TODO

- [x] Feature Gate this behind Elixir >1.14 – it uses `Macro.path/2`
- [x] Expand scope alias when they're defined with module attributes or variables

### CODE REVIEW

**Comment by gugahoa** [comment]
@lukaszsamson to ensure I'm not overstepping my bounds: This PR was made with the intention of discussing it all – if it's valuable or not; what approaches should be taken; what should make into the PR or not. I'm pretty open to discard it, or re-write from scratch after discussion.

Since I wanted to ensure it's possible to do it at all, I made a PR with working example instead of an issue to discuss.

**Comment by lukaszsamson** [comment]
Nice. I was intending to look into that at some point as well

**Comment by gugahoa** [comment]
Marking it as ready for review. CI is passing, the 3 jobs that aren't passing in this PR are also not passing in the main branch

**Comment by lukaszsamson** [comment]
Thanks

**Pull request merged**
