### PR TITLE
Add Ecto plugin

### LINKED ISSUE #104: Add ecto plugin
I'm working on a plugin to improve `Ecto` support for editors. The first two features are:

1. Improve snippets to provide the list of available types when completing `field` or `add`. Example:

image

2. Context-aware suggestions for `from`:

image

@lukaszsamson in the example above, how hard would be to identify the variable `u` as an instance of `%User{}`?

### PR DESCRIPTION
**Pull request by msaraiva**
Resolves #104.

This PR also adds support to signature help on functions without parentheses.

### CODE REVIEW

**Comment by axelson** [comment]
@msaraiva Does ElixirLS need a specific update to take advantage of this? Or does it just need to bump elixir_sense?

**Comment by msaraiva** [comment]
@axelson it will require an update. I'm working on the PR right now ;)

**Comment by msaraiva** [comment]
@axelson done! 

There ere a few cool things that were added since we last talked. One of them is the ability to add suggestions for option values. I already implemented this feature for `field`, `has_many`, `has_one`, `many_to_many` and `belongs_to`. Example:

image

We also list the available schemas after `in` for `from` and `joins`:

image

**Comment by msaraiva** [comment]
My next step is to create a generic plugin that can read information directly from the docs metadata so we don't have to hard code the options + values + docs. This way any project can provide information that can be read by ElixirSense automatically without the need for a specific plugin. This information can also be autogenerated by libraries like `nimble_options`. I'll have an example for `Surface` in a couple of days ;)

**Pull request merged**
