### PR TITLE
Fuzzy matching

### PR DESCRIPTION
**Pull request by princemaple**
related: https://github.com/elixir-lsp/elixir-ls/issues/466
image

Only applied fuzzy matching on module functions so far.

All these files could use this polish to enhance UX. How far do we want to go in 1 PR?

- lib/elixir_sense/plugins/option.ex
- lib/elixir_sense/providers/suggestion/reducers/type_specs.ex
- lib/elixir_sense/providers/suggestion/reducers/callbacks.ex
- lib/elixir_sense/providers/suggestion/reducers/struct.ex
- lib/elixir_sense/providers/suggestion/reducers/params.ex
- lib/elixir_sense/providers/suggestion/reducers/overridable.ex
- lib/elixir_sense/providers/suggestion/reducers/protocol.ex
- lib/elixir_sense/providers/suggestion/reducers/docs_snippets.ex
- lib/elixir_sense/providers/suggestion/complete.ex
- lib/elixir_sense/plugins/ecto/schema.ex

### CODE REVIEW

**Comment by princemaple** [comment]
The suggestion tests are kinda annoying now - they now return a lot more results because of fuzzy matching.

**Comment by princemaple** [comment]
@lukaszsamson @axelson @msaraiva 

I'd be most appreciative if some of you could review this before I go and fix the tests in ElixirLS, in case you have a different opinion about how the tests should be fixed.

**Comment by lukaszsamson** [comment]
Nice work @princemaple. I'm going to test it a bit tomorrow.

**Comment by princemaple** [comment]
Thanks. I'm quite enjoying it while coding today, so much that I'm willing to fix more tests so I can apply it in more scenarios.

**Comment by princemaple** [comment]
FYI the past week of using this patch has been very pleasant.

**Comment by lukaszsamson** [comment]
I did some testing and so far I like how it's working.

> All these files could use this polish to enhance UX. How far do we want to go in 1 PR?
lib/elixir_sense/plugins/option.ex
lib/elixir_sense/providers/suggestion/reducers/type_specs.ex
lib/elixir_sense/providers/suggestion/reducers/callbacks.ex
lib/elixir_sense/providers/suggestion/reducers/struct.ex
lib/elixir_sense/providers/suggestion/reducers/params.ex
lib/elixir_sense/providers/suggestion/reducers/overridable.ex
lib/elixir_sense/providers/suggestion/reducers/protocol.ex
lib/elixir_sense/providers/suggestion/reducers/docs_snippets.ex
lib/elixir_sense/providers/suggestion/complete.ex
lib/elixir_sense/plugins/ecto/schema.ex

Let's do them in follow up PRs. This one is already big. I'm not sure if callbacks, overridable and protocols are good candidates. Apart from those I'd include more suggestions from complete module: elixir/erlang modules, variables, attributes, map/struct keys. Elixir modules would probably work better with some letter downcasing.

**Review by lukaszsamson — APPROVED** [review]

**Pull request merged**
